name: iplock
main: net.gamerservices.iplock.iplock
version: 0.04
author: mixxit
website: http://www.gamerservices.net
description: >
    prevents users from logging in from multiple ip addresses (two boxing prevention)
commands:
    iplock:
        description: iplock refresh - reloads iplock.users